# Generated by Django 4.0.4 on 2022-05-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=255)),
                ('b_writer', models.CharField(max_length=50)),
                ('b_date', models.DateTimeField()),
            ],
        ),
    ]
